docs_dir: docs/
repo_url: https://github.com/username/{{ cookiecutter.project_slug }}
repo_name: .{{ cookiecutter.project_slug }}
site_name: {{ cookiecutter.project_slug }}

theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
extra:
  version:
    provider: mike
plugins:
  - include-markdown
  - search
  - tags
  - mkdocstrings:
      watch:
        - {{ cookiecutter.project_slug }}
